on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: jenkinacr.azurecr.io
        username: ${{ secrets.acr_jenkinacr_username }}
        password: ${{ secrets.acr_jenkinacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/aspnetcorelinuxdemo" -f  "aspnetcorelinuxdemo/Dockerfile" -t jenkinacr.azurecr.io/aksjenkin:${{ github.sha }}
        docker push jenkinacr.azurecr.io/aksjenkin:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksjenkin_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksjenkin0798 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksjenkin0798`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksjenkin0798
        container-registry-url: jenkinacr.azurecr.io
        container-registry-username: ${{ secrets.acr_jenkinacr_username }}
        container-registry-password: ${{ secrets.acr_jenkinacr_password }}
        secret-name: aksjenkindockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: aksjenkin0798
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          jenkinacr.azurecr.io/aksjenkin:${{ github.sha }}
        imagepullsecrets: |
          aksjenkindockerauth